### ISSUE TITLE
[Android] Build fails with compileSdkVersion 34

### ISSUE THREAD

**Issue by giaset** [stripe/stripe-identity-react-native#150] opened 2024-01-05 23:38 UTC
Hey all, recently bumped our compileSdkVersion up to 34 to support the latest version of intercom-react-native and now my builds are failing with the following errors

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform accompanist-themeadapter-material-0.32.0.aar (com.google.accompanist:accompanist-themeadapter-material:0.32.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /home/expo/.gradle/caches/transforms-3/2f8a3d0aee53c2f966489a67355c46d9/transformed/jetified-accompanist-themeadapter-material-0.32.0-runtime.jar.
         > Error while dexing.
   > Failed to transform accompanist-themeadapter-core-0.32.0.aar (com.google.accompanist:accompanist-themeadapter-core:0.32.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /home/expo/.gradle/caches/transforms-3/f895d8b2240e63eb2c699249188896bf/transformed/jetified-accompanist-themeadapter-core-0.32.0-runtime.jar.
         > Error while dexing.
   > Failed to transform kotlin-stdlib-1.9.0.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /home/expo/.gradle/caches/transforms-3/d00b0b172976cc1271cabf265090c43d/transformed/jetified-kotlin-stdlib-1.9.0.jar.
         > Error while dexing.
```

I ran `./gradlew app:dependencies` and traced that `accompanist-themeadapter` library back to `com.stripe.identity` (it seems like this library may be deprecated)

Anybody else experiencing this and/or know a workaround. Thanks!

**Comment by giaset** [comment] 2024-01-09 17:00
Hey @ccen-stripe just bumping this here. Any ideas?

**Comment by ccen-stripe** [comment] 2024-01-10 19:26
hi @giaset update: https://github.com/stripe/stripe-android/pull/7603 is being merged to upgrade the version to 34, will let you know once it's available in react native SDK

**Comment by giaset** [comment] 2024-01-10 19:27
Thanks for the quick turnaround @ccen-stripe!

**Comment by ccen-stripe** [comment] 2024-01-18 01:37
Hi @giaset we just tried to reproduce your issue with current release and thought this is _not_ a compileSDK version issue from the native Android SDK, we were able to build with existing versions on an app with compileSDK 34. 
The compile issues from your app seems happening on a certain combination of RN, android gradle plugin(AGP), gradle and kotlin verions. From your log, it seems you are using kotlin `1.9.0`, we tried to reproduce the issue in different settings but the app was built properly, here is what we tried:

* `react-native:0.73.2`, with default AGP version `8.1.x`,  `kotlinVersion:1.8.0` or `kotlinVersion:1.9.0` ([link](https://github.com/ccen-stripe/rn073/blob/main/package.json))
* `react-native:0.70.6`, with AGP version `7.2.2`, `kotlinVersion:1.8.0` or `kotlinVersion:1.9.0` ([link](https://github.com/ccen-stripe/IdentityRNTest/blob/main/package.json))
* `react-native:0.69.1`, with AGP version `7.2.2`,`kotlinVersion:1.8.0` or `kotlinVersion:1.9.0` ([link](https://github.com/stripe/stripe-identity-react-native/blob/main/example/package.json))

Please share with your app's android settings for us to poinpoint the issue, specifically -`package.json`, `android/gradle/wrapper/gradle-wrapper.properties`, `android/build.gradle` and `android/app/build.gradle` so we could reproduce your dev env.

**Comment by ccen-stripe** [comment] 2024-01-19 18:48
Also tried with the latest 4 release (6.1.0 to 6.4.0) with [intercom](https://www.npmjs.com/package/@intercom/intercom-react-native?activeTab=versions) but can't reproduce the issue, FYI here is the android with identity and intercom, on an app at compileSdkVersion 34, kotlinVersion 1.9:

![Screenshot 2024-01-19 at 10 45 12 AM](https://github.com/stripe/stripe-identity-react-native/assets/79880926/f54cc4af-6c23-432f-b58f-646ab7cd0c95)

**Comment by ccen-stripe** [comment] 2024-01-24 17:47
Update: upgrading to Expo 50 and bump compile SDK version to 34 fixed this issue

**Closed** 2024-02-08 22:36 UTC
